-- ============================================================
-- 02_seed_data.sql
-- Datos de prueba para Proyecto 2 - Centros de Evaluación de Manejo
-- Ejecutar conectado como CEM_USER.
-- Este script es re-ejecutable: borra datos existentes y vuelve a cargar.
-- ============================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET DEFINE OFF;

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = CEM_USER;


ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

-- Limpieza en orden inverso por llaves foráneas
DELETE FROM RESPUESTA_PRACTICO_USUARIO;
DELETE FROM RESPUESTA_USUARIO;
DELETE FROM EXAMEN;
DELETE FROM REGISTRO;
DELETE FROM UBICACION;
DELETE FROM PREGUNTAS_PRACTICO;
DELETE FROM PREGUNTAS;
DELETE FROM CORRELATIVO;
DELETE FROM MUNICIPIO;
DELETE FROM ESCUELA;
DELETE FROM CENTRO;
DELETE FROM DEPARTAMENTO;

-- ============================================================
-- Tablas base
-- ============================================================

INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE, CODIGO) VALUES (1, 'Guatemala', '01');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE, CODIGO) VALUES (2, 'Sacatepéquez', '03');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE, CODIGO) VALUES (3, 'Escuintla', '05');

INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, CODIGO, DEPARTAMENTO_ID_DEPARTAMENTO) VALUES (1, 'Guatemala', '01', 1);
INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, CODIGO, DEPARTAMENTO_ID_DEPARTAMENTO) VALUES (2, 'Mixco', '02', 1);
INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, CODIGO, DEPARTAMENTO_ID_DEPARTAMENTO) VALUES (3, 'Villa Nueva', '03', 1);
INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, CODIGO, DEPARTAMENTO_ID_DEPARTAMENTO) VALUES (4, 'Escuintla', '01', 3);
INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, CODIGO, DEPARTAMENTO_ID_DEPARTAMENTO) VALUES (5, 'Antigua Guatemala', '01', 2);

INSERT INTO CENTRO (ID_CENTRO, NOMBRE) VALUES (1, 'Centro de Evaluación Zona 12');
INSERT INTO CENTRO (ID_CENTRO, NOMBRE) VALUES (2, 'Centro de Evaluación Antigua Guatemala');
INSERT INTO CENTRO (ID_CENTRO, NOMBRE) VALUES (3, 'Centro de Evaluación Escuintla');

INSERT INTO ESCUELA (ID_ESCUELA, NOMBRE, DIRECCION, ACUERDO) VALUES (1, 'Escuela de Manejo AutoMaster', 'Avenida Reforma 15-45, Zona 10', 'ESC-AM-001');
INSERT INTO ESCUELA (ID_ESCUELA, NOMBRE, DIRECCION, ACUERDO) VALUES (2, 'Academia Vial GuateDrive', 'Boulevard Los Próceres 18-20, Zona 10', 'ESC-GD-002');
INSERT INTO ESCUELA (ID_ESCUELA, NOMBRE, DIRECCION, ACUERDO) VALUES (3, 'Instituto de Conducción Segura', 'Calzada Roosevelt 25-30, Zona 11', 'ESC-ICS-003');

-- Relación escuela-centro
INSERT INTO UBICACION (ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO) VALUES (1, 1);
INSERT INTO UBICACION (ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO) VALUES (1, 2);
INSERT INTO UBICACION (ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO) VALUES (2, 1);
-- Esta relacion se agrega porque REGISTRO 5 referencia Escuela 2 con Centro 2.
-- Sin esta fila, la FK REGISTRO_UBICACION_FK fallaria.
INSERT INTO UBICACION (ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO) VALUES (2, 2);
INSERT INTO UBICACION (ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO) VALUES (3, 2);
INSERT INTO UBICACION (ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO) VALUES (3, 3);

-- ============================================================
-- Registros y exámenes
-- ============================================================

INSERT INTO REGISTRO (ID_REGISTRO, UBICACION_ESCUELA_ID_ESCUELA, UBICACION_CENTRO_ID_CENTRO, MUNICIPIO_ID_MUNICIPIO, MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO, FECHA, TIPO_TRAMITE, TIPO_LICENCIA, NOMBRE_COMPLETO, GENERO)
VALUES (1, 1, 1, 1, 1, DATE '2025-01-15', 'Licencia de Conducir', 'A', 'Juan Carlos López García', 'M');
INSERT INTO REGISTRO (ID_REGISTRO, UBICACION_ESCUELA_ID_ESCUELA, UBICACION_CENTRO_ID_CENTRO, MUNICIPIO_ID_MUNICIPIO, MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO, FECHA, TIPO_TRAMITE, TIPO_LICENCIA, NOMBRE_COMPLETO, GENERO)
VALUES (2, 1, 2, 2, 1, DATE '2025-01-15', 'Licencia de Conducir', 'B', 'María Elena Rodríguez Morales', 'F');
INSERT INTO REGISTRO (ID_REGISTRO, UBICACION_ESCUELA_ID_ESCUELA, UBICACION_CENTRO_ID_CENTRO, MUNICIPIO_ID_MUNICIPIO, MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO, FECHA, TIPO_TRAMITE, TIPO_LICENCIA, NOMBRE_COMPLETO, GENERO)
VALUES (3, 2, 1, 3, 1, DATE '2025-01-16', 'Licencia de Conducir', 'A', 'Carlos Alberto Méndez Castillo', 'M');
INSERT INTO REGISTRO (ID_REGISTRO, UBICACION_ESCUELA_ID_ESCUELA, UBICACION_CENTRO_ID_CENTRO, MUNICIPIO_ID_MUNICIPIO, MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO, FECHA, TIPO_TRAMITE, TIPO_LICENCIA, NOMBRE_COMPLETO, GENERO)
VALUES (4, 3, 3, 4, 3, DATE '2025-01-17', 'Licencia de Conducir', 'A', 'Ana Sofía Guerrero Díaz', 'F');
INSERT INTO REGISTRO (ID_REGISTRO, UBICACION_ESCUELA_ID_ESCUELA, UBICACION_CENTRO_ID_CENTRO, MUNICIPIO_ID_MUNICIPIO, MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO, FECHA, TIPO_TRAMITE, TIPO_LICENCIA, NOMBRE_COMPLETO, GENERO)
VALUES (5, 2, 2, 5, 2, DATE '2025-01-18', 'Licencia de Conducir', 'B', 'Pedro José Hernández Ruiz', 'M');

INSERT INTO CORRELATIVO (ID_CORRELATIVO, FECHA, NO_EXAMEN) VALUES (1, DATE '2025-01-15', 1);
INSERT INTO CORRELATIVO (ID_CORRELATIVO, FECHA, NO_EXAMEN) VALUES (2, DATE '2025-01-15', 2);
INSERT INTO CORRELATIVO (ID_CORRELATIVO, FECHA, NO_EXAMEN) VALUES (3, DATE '2025-01-16', 3);
INSERT INTO CORRELATIVO (ID_CORRELATIVO, FECHA, NO_EXAMEN) VALUES (4, DATE '2025-01-17', 4);
INSERT INTO CORRELATIVO (ID_CORRELATIVO, FECHA, NO_EXAMEN) VALUES (5, DATE '2025-01-18', 5);

INSERT INTO EXAMEN (ID_EXAMEN, REGISTRO_ID_REGISTRO, CORRELATIVO_ID_CORRELATIVO, REGISTRO_UBICACION_ESCUELA_ID_ESCUELA, REGISTRO_UBICACION_CENTRO_ID_CENTRO, REGISTRO_MUNICIPIO_ID_MUNICIPIO, REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO) VALUES (1, 1, 1, 1, 1, 1, 1);
INSERT INTO EXAMEN (ID_EXAMEN, REGISTRO_ID_REGISTRO, CORRELATIVO_ID_CORRELATIVO, REGISTRO_UBICACION_ESCUELA_ID_ESCUELA, REGISTRO_UBICACION_CENTRO_ID_CENTRO, REGISTRO_MUNICIPIO_ID_MUNICIPIO, REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO) VALUES (2, 2, 2, 1, 2, 2, 1);
INSERT INTO EXAMEN (ID_EXAMEN, REGISTRO_ID_REGISTRO, CORRELATIVO_ID_CORRELATIVO, REGISTRO_UBICACION_ESCUELA_ID_ESCUELA, REGISTRO_UBICACION_CENTRO_ID_CENTRO, REGISTRO_MUNICIPIO_ID_MUNICIPIO, REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO) VALUES (3, 3, 3, 2, 1, 3, 1);
INSERT INTO EXAMEN (ID_EXAMEN, REGISTRO_ID_REGISTRO, CORRELATIVO_ID_CORRELATIVO, REGISTRO_UBICACION_ESCUELA_ID_ESCUELA, REGISTRO_UBICACION_CENTRO_ID_CENTRO, REGISTRO_MUNICIPIO_ID_MUNICIPIO, REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO) VALUES (4, 4, 4, 3, 3, 4, 3);
INSERT INTO EXAMEN (ID_EXAMEN, REGISTRO_ID_REGISTRO, CORRELATIVO_ID_CORRELATIVO, REGISTRO_UBICACION_ESCUELA_ID_ESCUELA, REGISTRO_UBICACION_CENTRO_ID_CENTRO, REGISTRO_MUNICIPIO_ID_MUNICIPIO, REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO) VALUES (5, 5, 5, 2, 2, 5, 2);

-- ============================================================
-- Preguntas teóricas y prácticas
-- ============================================================

INSERT INTO PREGUNTAS (ID_PREGUNTA, PREGUNTA_TEXTO, RESPUESTA_A, RESPUESTA_B, RESPUESTA_C, RESPUESTA_D, RESPUESTA_CORRECTA)
VALUES (1, '¿Cuál es la distancia mínima que debe mantener entre vehículos en carretera?', '2 metros', '3 segundos de distancia', '5 metros', '1 segundo de distancia', 'B');
INSERT INTO PREGUNTAS (ID_PREGUNTA, PREGUNTA_TEXTO, RESPUESTA_A, RESPUESTA_B, RESPUESTA_C, RESPUESTA_D, RESPUESTA_CORRECTA)
VALUES (2, '¿Qué significa una señal de alto?', 'Reducir velocidad', 'Detenerse completamente', 'Ceder el paso', 'Continuar con precaución', 'B');
INSERT INTO PREGUNTAS (ID_PREGUNTA, PREGUNTA_TEXTO, RESPUESTA_A, RESPUESTA_B, RESPUESTA_C, RESPUESTA_D, RESPUESTA_CORRECTA)
VALUES (3, '¿Cuál es el límite de velocidad en zona escolar?', '20 km/h', '30 km/h', '40 km/h', '50 km/h', 'A');
INSERT INTO PREGUNTAS (ID_PREGUNTA, PREGUNTA_TEXTO, RESPUESTA_A, RESPUESTA_B, RESPUESTA_C, RESPUESTA_D, RESPUESTA_CORRECTA)
VALUES (4, '¿Qué debe hacer al ver una ambulancia con sirena activada?', 'Mantener velocidad', 'Acelerar para salir del camino', 'Orillarse y detenerse', 'Ignorar la sirena', 'C');

INSERT INTO PREGUNTAS_PRACTICO (ID_PREGUNTA_PRACTICO, PREGUNTA_TEXTO, PUNTEO) VALUES (1, 'Realizar estacionamiento en paralelo en un espacio de 6 metros', 20);
INSERT INTO PREGUNTAS_PRACTICO (ID_PREGUNTA_PRACTICO, PREGUNTA_TEXTO, PUNTEO) VALUES (2, 'Conducir en reversa por 50 metros manteniendo trayectoria recta', 15);
INSERT INTO PREGUNTAS_PRACTICO (ID_PREGUNTA_PRACTICO, PREGUNTA_TEXTO, PUNTEO) VALUES (3, 'Maniobra de tres puntos en espacio reducido', 25);
INSERT INTO PREGUNTAS_PRACTICO (ID_PREGUNTA_PRACTICO, PREGUNTA_TEXTO, PUNTEO) VALUES (4, 'Conducción en zona urbana respetando señales de tránsito', 30);

-- Respuestas teóricas
INSERT INTO RESPUESTA_USUARIO (PREGUNTAS_ID_PREGUNTA, EXAMEN_ID_EXAMEN, RESPUESTA) VALUES (1, 1, 'B');
INSERT INTO RESPUESTA_USUARIO (PREGUNTAS_ID_PREGUNTA, EXAMEN_ID_EXAMEN, RESPUESTA) VALUES (2, 1, 'B');
INSERT INTO RESPUESTA_USUARIO (PREGUNTAS_ID_PREGUNTA, EXAMEN_ID_EXAMEN, RESPUESTA) VALUES (3, 2, 'A');
INSERT INTO RESPUESTA_USUARIO (PREGUNTAS_ID_PREGUNTA, EXAMEN_ID_EXAMEN, RESPUESTA) VALUES (4, 2, 'C');
INSERT INTO RESPUESTA_USUARIO (PREGUNTAS_ID_PREGUNTA, EXAMEN_ID_EXAMEN, RESPUESTA) VALUES (1, 3, 'B');
INSERT INTO RESPUESTA_USUARIO (PREGUNTAS_ID_PREGUNTA, EXAMEN_ID_EXAMEN, RESPUESTA) VALUES (2, 3, 'A');

-- Respuestas prácticas
INSERT INTO RESPUESTA_PRACTICO_USUARIO (PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO, EXAMEN_ID_EXAMEN, NOTA) VALUES (1, 1, 18);
INSERT INTO RESPUESTA_PRACTICO_USUARIO (PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO, EXAMEN_ID_EXAMEN, NOTA) VALUES (2, 1, 13);
INSERT INTO RESPUESTA_PRACTICO_USUARIO (PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO, EXAMEN_ID_EXAMEN, NOTA) VALUES (3, 2, 22);
INSERT INTO RESPUESTA_PRACTICO_USUARIO (PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO, EXAMEN_ID_EXAMEN, NOTA) VALUES (4, 2, 28);
INSERT INTO RESPUESTA_PRACTICO_USUARIO (PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO, EXAMEN_ID_EXAMEN, NOTA) VALUES (1, 3, 15);

-- Reiniciar secuencias para que futuros inserts automáticos no repitan IDs.
ALTER SEQUENCE DEPARTAMENTO_ID_DEPARTAMENTO_SEQ RESTART START WITH 4;
ALTER SEQUENCE MUNICIPIO_ID_MUNICIPIO_SEQ RESTART START WITH 6;
ALTER SEQUENCE CENTRO_ID_CENTRO_SEQ RESTART START WITH 4;
ALTER SEQUENCE ESCUELA_ID_ESCUELA_SEQ RESTART START WITH 4;
ALTER SEQUENCE REGISTRO_ID_REGISTRO_SEQ RESTART START WITH 6;
ALTER SEQUENCE CORRELATIVO_ID_CORRELATIVO_SEQ RESTART START WITH 6;
ALTER SEQUENCE EXAMEN_ID_EXAMEN_SEQ RESTART START WITH 6;
ALTER SEQUENCE PREGUNTAS_ID_PREGUNTA_SEQ RESTART START WITH 5;
ALTER SEQUENCE PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO_SEQ RESTART START WITH 5;

COMMIT;

-- ============================================================
-- Consultas rápidas de verificación
-- ============================================================

SELECT 'DEPARTAMENTO' AS TABLA, COUNT(*) AS CANTIDAD FROM DEPARTAMENTO
UNION ALL SELECT 'MUNICIPIO', COUNT(*) FROM MUNICIPIO
UNION ALL SELECT 'CENTRO', COUNT(*) FROM CENTRO
UNION ALL SELECT 'ESCUELA', COUNT(*) FROM ESCUELA
UNION ALL SELECT 'UBICACION', COUNT(*) FROM UBICACION
UNION ALL SELECT 'REGISTRO', COUNT(*) FROM REGISTRO
UNION ALL SELECT 'CORRELATIVO', COUNT(*) FROM CORRELATIVO
UNION ALL SELECT 'EXAMEN', COUNT(*) FROM EXAMEN
UNION ALL SELECT 'PREGUNTAS', COUNT(*) FROM PREGUNTAS
UNION ALL SELECT 'PREGUNTAS_PRACTICO', COUNT(*) FROM PREGUNTAS_PRACTICO
UNION ALL SELECT 'RESPUESTA_USUARIO', COUNT(*) FROM RESPUESTA_USUARIO
UNION ALL SELECT 'RESPUESTA_PRACTICO_USUARIO', COUNT(*) FROM RESPUESTA_PRACTICO_USUARIO
