-- Generado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   en:        2026-03-02 11:42:55 CST
--   sitio:      Oracle Database 21c
--   tipo:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE CENTRO 
    ( 
     ID_CENTRO NUMBER (10)  NOT NULL , 
     NOMBRE    VARCHAR2 (120 CHAR)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX JAIRO.CENTRO_PK ON CENTRO 
    ( 
     ID_CENTRO ASC 
    ) 
;

ALTER TABLE CENTRO 
    ADD CONSTRAINT CENTRO_PK PRIMARY KEY ( ID_CENTRO ) ;

CREATE TABLE CORRELATIVO 
    ( 
     ID_CORRELATIVO NUMBER (10)  NOT NULL , 
     FECHA          DATE  NOT NULL , 
     NO_EXAMEN      NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE CORRELATIVO 
    ADD CONSTRAINT CORRELATIVO_NO_EXAMEN_CK 
    CHECK (no_examen >= 1) 
;
CREATE UNIQUE INDEX JAIRO.CORRELATIVO_PK ON CORRELATIVO 
    ( 
     ID_CORRELATIVO ASC 
    ) 
;

ALTER TABLE CORRELATIVO 
    ADD CONSTRAINT CORRELATIVO_PK PRIMARY KEY ( ID_CORRELATIVO ) ;

CREATE TABLE DEPARTAMENTO 
    ( 
     ID_DEPARTAMENTO NUMBER (10)  NOT NULL , 
     NOMBRE          VARCHAR2 (100 CHAR)  NOT NULL , 
     CODIGO          NUMBER (10) 
    ) 
;
CREATE UNIQUE INDEX JAIRO.DEPARTAMENTO_PK ON DEPARTAMENTO 
    ( 
     ID_DEPARTAMENTO ASC 
    ) 
;

ALTER TABLE DEPARTAMENTO 
    ADD CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY ( ID_DEPARTAMENTO ) ;

CREATE TABLE ESCUELA 
    ( 
     ID_ESCUELA NUMBER (10)  NOT NULL , 
     NOMBRE     VARCHAR2 (120 CHAR)  NOT NULL , 
     DIRECCION  VARCHAR2 (250 CHAR) , 
     ACUERDO    VARCHAR2 (30 CHAR) 
    ) 
;
CREATE UNIQUE INDEX JAIRO.ESCUELA_PK ON ESCUELA 
    ( 
     ID_ESCUELA ASC 
    ) 
;

ALTER TABLE ESCUELA 
    ADD CONSTRAINT ESCUELA_PK PRIMARY KEY ( ID_ESCUELA ) ;

CREATE TABLE EXAMEN 
    ( 
     ID_EXAMEN                  NUMBER (10)  NOT NULL , 
     REGISTRO_ID_REGISTRO       NUMBER (10)  NOT NULL , 
     CORRELATIVO_ID_CORRELATIVO NUMBER (10)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX JAIRO.EXAMEN_PK ON EXAMEN 
    ( 
     ID_EXAMEN ASC 
    ) 
;

ALTER TABLE EXAMEN 
    ADD CONSTRAINT EXAMEN_PK PRIMARY KEY ( ID_EXAMEN ) ;

CREATE TABLE MUNICIPIO 
    ( 
     ID_MUNICIPIO                 NUMBER (10)  NOT NULL , 
     DEPARTAMENTO_ID_DEPARTAMENTO NUMBER (10)  NOT NULL , 
     NOMBRE                       VARCHAR2 (120 CHAR)  NOT NULL , 
     CODIGO                       NUMBER (10) 
    ) 
;
CREATE UNIQUE INDEX JAIRO.MUNICIPIO_PK ON MUNICIPIO 
    ( 
     ID_MUNICIPIO ASC 
    ) 
;

ALTER TABLE MUNICIPIO 
    ADD CONSTRAINT MUNICIPIO_PK PRIMARY KEY ( ID_MUNICIPIO ) ;

CREATE TABLE PREGUNTA 
    ( 
     ID_PREGUNTA NUMBER (10)  NOT NULL , 
     TEXTO       VARCHAR2 (500 CHAR)  NOT NULL , 
     RES1        VARCHAR2 (200 CHAR)  NOT NULL , 
     RES2        VARCHAR2 (200 CHAR)  NOT NULL , 
     RES3        VARCHAR2 (200 CHAR)  NOT NULL , 
     RES4        VARCHAR2 (200 CHAR)  NOT NULL , 
     CORRECTA    NUMBER (1)  NOT NULL 
    ) 
;

ALTER TABLE PREGUNTA 
    ADD CONSTRAINT PREGUNTA_CORRECTA_CK 
    CHECK (CORRECTA IN (1, 2, 3, 4)) 
;
CREATE UNIQUE INDEX JAIRO.PREGUNTA_PK ON PREGUNTA 
    ( 
     ID_PREGUNTA ASC 
    ) 
;

ALTER TABLE PREGUNTA 
    ADD CONSTRAINT PREGUNTA_PK PRIMARY KEY ( ID_PREGUNTA ) ;

CREATE TABLE PREGUNTA_PRACTICO 
    ( 
     ID_PREG_PRACTICO NUMBER (10)  NOT NULL , 
     TEXTO            VARCHAR2 (500 CHAR)  NOT NULL , 
     PUNTEO           NUMBER (3) DEFAULT 10  NOT NULL 
    ) 
;

ALTER TABLE PREGUNTA_PRACTICO 
    ADD CONSTRAINT PREGUNTA_PRACTICO_PUNTEO_CK 
    CHECK (PUNTEO BETWEEN 0 AND 100) 
;
CREATE UNIQUE INDEX JAIRO.PREGUNTA_PRACTICO_PK ON PREGUNTA_PRACTICO 
    ( 
     ID_PREG_PRACTICO ASC 
    ) 
;

ALTER TABLE PREGUNTA_PRACTICO 
    ADD CONSTRAINT PREGUNTA_PRACTICO_PK PRIMARY KEY ( ID_PREG_PRACTICO ) ;

CREATE TABLE REGISTRO 
    ( 
     ID_REGISTRO            NUMBER (10)  NOT NULL , 
     ESCUELA_ID_ESCUELA     NUMBER (10)  NOT NULL , 
     CENTRO_ID_CENTRO       NUMBER (10)  NOT NULL , 
     MUNICIPIO_ID_MUNICIPIO NUMBER (10)  NOT NULL , 
     FECHA                  DATE  NOT NULL , 
     T_TRAMITE              VARCHAR2 (30 CHAR)  NOT NULL , 
     T_LICENCIA             VARCHAR2 (5 CHAR)  NOT NULL , 
     NOMBRE_COMPLETO        VARCHAR2 (150 CHAR)  NOT NULL , 
     GENERO                 CHAR (1 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE REGISTRO 
    ADD CONSTRAINT REGISTRO_GENERO_CK 
    CHECK (GENERO IN ('F', 'M')) 
;
CREATE UNIQUE INDEX JAIRO.REGISTRO_PK ON REGISTRO 
    ( 
     ID_REGISTRO ASC 
    ) 
;

ALTER TABLE REGISTRO 
    ADD CONSTRAINT REGISTRO_PK PRIMARY KEY ( ID_REGISTRO ) ;

CREATE TABLE RESPUESTA_PRACTICO_USUARIO 
    ( 
     ID_RESPUESTA_PRACTICO              NUMBER (10)  NOT NULL , 
     PREGUNTA_PRACTICO_ID_PREG_PRACTICO NUMBER (10)  NOT NULL , 
     EXAMEN_ID_EXAMEN                   NUMBER (10)  NOT NULL , 
     NOTA                               NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE RESPUESTA_PRACTICO_USUARIO 
    ADD CONSTRAINT RESPUESTA_PRACTICO_USUARIO_NOTA_CK 
    CHECK (NOTA BETWEEN 0 AND 10) 
;
CREATE UNIQUE INDEX JAIRO.RESPUESTA_PRACTICO_USUARIO_PK ON RESPUESTA_PRACTICO_USUARIO 
    ( 
     ID_RESPUESTA_PRACTICO ASC 
    ) 
;

ALTER TABLE RESPUESTA_PRACTICO_USUARIO 
    ADD CONSTRAINT RESPUESTA_PRACTICO_USUARIO_PK PRIMARY KEY ( ID_RESPUESTA_PRACTICO ) ;

CREATE TABLE RESPUESTA_USUARIO 
    ( 
     ID_RESPUESTA_USUARIO NUMBER (10)  NOT NULL , 
     PREGUNTA_ID_PREGUNTA NUMBER (10)  NOT NULL , 
     EXAMEN_ID_EXAMEN     NUMBER (10)  NOT NULL , 
     RESPUESTA            NUMBER (1)  NOT NULL 
    ) 
;

ALTER TABLE RESPUESTA_USUARIO 
    ADD CONSTRAINT RESPUESTA_USUARIO_RESPUESTA_CK 
    CHECK (RESPUESTA IN (1, 2, 3, 4)) 
;
CREATE UNIQUE INDEX JAIRO.RESPUESTA_USUARIO_PK ON RESPUESTA_USUARIO 
    ( 
     ID_RESPUESTA_USUARIO ASC 
    ) 
;

ALTER TABLE RESPUESTA_USUARIO 
    ADD CONSTRAINT RESPUESTA_USUARIO_PK PRIMARY KEY ( ID_RESPUESTA_USUARIO ) ;

CREATE TABLE UBICACION 
    ( 
     ESCUELA_ID_ESCUELA NUMBER (10)  NOT NULL , 
     CENTRO_ID_CENTRO   NUMBER (10)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX JAIRO.UBICACION_PK ON UBICACION 
    ( 
     ESCUELA_ID_ESCUELA ASC , 
     CENTRO_ID_CENTRO ASC 
    ) 
;

ALTER TABLE UBICACION 
    ADD CONSTRAINT UBICACION_PK PRIMARY KEY ( ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO ) ;

ALTER TABLE EXAMEN 
    ADD CONSTRAINT EXAMEN_CORRELATIVO_FK FOREIGN KEY 
    ( 
     CORRELATIVO_ID_CORRELATIVO
    ) 
    REFERENCES CORRELATIVO 
    ( 
     ID_CORRELATIVO
    ) 
;

ALTER TABLE EXAMEN 
    ADD CONSTRAINT EXAMEN_REGISTRO_FK FOREIGN KEY 
    ( 
     REGISTRO_ID_REGISTRO
    ) 
    REFERENCES REGISTRO 
    ( 
     ID_REGISTRO
    ) 
;

ALTER TABLE MUNICIPIO 
    ADD CONSTRAINT MUNICIPIO_DEPARTAMENTO_FK FOREIGN KEY 
    ( 
     DEPARTAMENTO_ID_DEPARTAMENTO
    ) 
    REFERENCES DEPARTAMENTO 
    ( 
     ID_DEPARTAMENTO
    ) 
;

ALTER TABLE REGISTRO 
    ADD CONSTRAINT REGISTRO_CENTRO_FK FOREIGN KEY 
    ( 
     CENTRO_ID_CENTRO
    ) 
    REFERENCES CENTRO 
    ( 
     ID_CENTRO
    ) 
;

ALTER TABLE REGISTRO 
    ADD CONSTRAINT REGISTRO_ESCUELA_FK FOREIGN KEY 
    ( 
     ESCUELA_ID_ESCUELA
    ) 
    REFERENCES ESCUELA 
    ( 
     ID_ESCUELA
    ) 
;

ALTER TABLE REGISTRO 
    ADD CONSTRAINT REGISTRO_MUNICIPIO_FK FOREIGN KEY 
    ( 
     MUNICIPIO_ID_MUNICIPIO
    ) 
    REFERENCES MUNICIPIO 
    ( 
     ID_MUNICIPIO
    ) 
;

ALTER TABLE RESPUESTA_PRACTICO_USUARIO 
    ADD CONSTRAINT RESPUESTA_PRACTICO_USUARIO_EXAMEN_FK FOREIGN KEY 
    ( 
     EXAMEN_ID_EXAMEN
    ) 
    REFERENCES EXAMEN 
    ( 
     ID_EXAMEN
    ) 
;

ALTER TABLE RESPUESTA_PRACTICO_USUARIO 
    ADD CONSTRAINT RESPUESTA_PRACTICO_USUARIO_PREGUNTA_PRACTICO_FK FOREIGN KEY 
    ( 
     PREGUNTA_PRACTICO_ID_PREG_PRACTICO
    ) 
    REFERENCES PREGUNTA_PRACTICO 
    ( 
     ID_PREG_PRACTICO
    ) 
;

ALTER TABLE RESPUESTA_USUARIO 
    ADD CONSTRAINT RESPUESTA_USUARIO_EXAMEN_FK FOREIGN KEY 
    ( 
     EXAMEN_ID_EXAMEN
    ) 
    REFERENCES EXAMEN 
    ( 
     ID_EXAMEN
    ) 
;

ALTER TABLE RESPUESTA_USUARIO 
    ADD CONSTRAINT RESPUESTA_USUARIO_PREGUNTA_FK FOREIGN KEY 
    ( 
     PREGUNTA_ID_PREGUNTA
    ) 
    REFERENCES PREGUNTA 
    ( 
     ID_PREGUNTA
    ) 
;

ALTER TABLE UBICACION 
    ADD CONSTRAINT UBICACION_CENTRO_FK FOREIGN KEY 
    ( 
     CENTRO_ID_CENTRO
    ) 
    REFERENCES CENTRO 
    ( 
     ID_CENTRO
    ) 
;

ALTER TABLE UBICACION 
    ADD CONSTRAINT UBICACION_ESCUELA_FK FOREIGN KEY 
    ( 
     ESCUELA_ID_ESCUELA
    ) 
    REFERENCES ESCUELA 
    ( 
     ID_ESCUELA
    ) 
;



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                            12
-- ALTER TABLE                             30
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
