services:
  oracle-db:
    image: gvenzl/oracle-xe:21
    container_name: sbd1_proyecto2_oracle
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: CEM_USER
      APP_USER_PASSWORD: cem123
    volumes:
      - oracle-proyecto2-data:/opt/oracle/oradata
      - ./database/init:/container-entrypoint-initdb.d
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sbd1_proyecto2_api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_USER: CEM_USER
      DB_PASSWORD: cem123
      DB_CONNECT_STRING: oracle-db:1521/XEPDB1
    depends_on:
      - oracle-db
    restart: unless-stopped

volumes:
  oracle-proyecto2-data: