-- Generado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   en:        2026-04-27 17:14:56 CST
--   sitio:      Oracle Database 21c
--   tipo:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE CEM_USER.CENTRO 
    ( 
     ID_CENTRO NUMBER  NOT NULL , 
     NOMBRE    VARCHAR2 (150 BYTE)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX CEM_USER.PK_CENTRO ON CEM_USER.CENTRO 
    ( 
     ID_CENTRO ASC 
    ) 
;

ALTER TABLE CEM_USER.CENTRO 
    ADD CONSTRAINT CENTRO_PK PRIMARY KEY ( ID_CENTRO ) ;

CREATE TABLE CEM_USER.CORRELATIVO 
    ( 
     ID_CORRELATIVO NUMBER  NOT NULL , 
     FECHA          DATE  NOT NULL , 
     NO_EXAMEN      NUMBER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX CEM_USER.PK_CORRELATIVO ON CEM_USER.CORRELATIVO 
    ( 
     ID_CORRELATIVO ASC 
    ) 
;
CREATE UNIQUE INDEX CEM_USER.UK_CORRELATIVO_FECHA_NO ON CEM_USER.CORRELATIVO 
    ( 
     FECHA ASC , 
     NO_EXAMEN ASC 
    ) 
;

ALTER TABLE CEM_USER.CORRELATIVO 
    ADD CONSTRAINT CORRELATIVO_PK PRIMARY KEY ( ID_CORRELATIVO ) ;

ALTER TABLE CEM_USER.CORRELATIVO 
    ADD CONSTRAINT CORRELATIVO_FECHA_NO_EXAMEN_UN UNIQUE ( FECHA , NO_EXAMEN ) ;

CREATE TABLE CEM_USER.DEPARTAMENTO 
    ( 
     ID_DEPARTAMENTO NUMBER  NOT NULL , 
     NOMBRE          VARCHAR2 (100 BYTE)  NOT NULL , 
     CODIGO          VARCHAR2 (10 BYTE)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX CEM_USER.PK_DEPARTAMENTO ON CEM_USER.DEPARTAMENTO 
    ( 
     ID_DEPARTAMENTO ASC 
    ) 
;
CREATE UNIQUE INDEX CEM_USER.UK_DEPARTAMENTO_CODIGO ON CEM_USER.DEPARTAMENTO 
    ( 
     CODIGO ASC 
    ) 
;

ALTER TABLE CEM_USER.DEPARTAMENTO 
    ADD CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY ( ID_DEPARTAMENTO ) ;

ALTER TABLE CEM_USER.DEPARTAMENTO 
    ADD CONSTRAINT DEPARTAMENTO_CODIGO_UN UNIQUE ( CODIGO ) ;

CREATE TABLE CEM_USER.ESCUELA 
    ( 
     ID_ESCUELA NUMBER  NOT NULL , 
     NOMBRE     VARCHAR2 (150 BYTE)  NOT NULL , 
     DIRECCION  VARCHAR2 (250 BYTE)  NOT NULL , 
     ACUERDO    VARCHAR2 (50 BYTE)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX CEM_USER.PK_ESCUELA ON CEM_USER.ESCUELA 
    ( 
     ID_ESCUELA ASC 
    ) 
;
CREATE UNIQUE INDEX CEM_USER.UK_ESCUELA_ACUERDO ON CEM_USER.ESCUELA 
    ( 
     ACUERDO ASC 
    ) 
;

ALTER TABLE CEM_USER.ESCUELA 
    ADD CONSTRAINT ESCUELA_PK PRIMARY KEY ( ID_ESCUELA ) ;

ALTER TABLE CEM_USER.ESCUELA 
    ADD CONSTRAINT ESCUELA_ACUERDO_UN UNIQUE ( ACUERDO ) ;

CREATE TABLE CEM_USER.EXAMEN 
    ( 
     ID_EXAMEN                                       NUMBER  NOT NULL , 
     REGISTRO_ID_REGISTRO                            NUMBER  NOT NULL , 
     CORRELATIVO_ID_CORRELATIVO                      NUMBER  NOT NULL , 
     REGISTRO_UBICACION_ESCUELA_ID_ESCUELA           NUMBER  NOT NULL , 
     REGISTRO_UBICACION_CENTRO_ID_CENTRO             NUMBER  NOT NULL , 
     REGISTRO_MUNICIPIO_ID_MUNICIPIO                 NUMBER  NOT NULL , 
     REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO NUMBER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX CEM_USER.PK_EXAMEN ON CEM_USER.EXAMEN 
    ( 
     ID_EXAMEN ASC 
    ) 
;

ALTER TABLE CEM_USER.EXAMEN 
    ADD CONSTRAINT EXAMEN_PK PRIMARY KEY ( ID_EXAMEN ) ;

CREATE TABLE CEM_USER.MUNICIPIO 
    ( 
     ID_MUNICIPIO                 NUMBER  NOT NULL , 
     NOMBRE                       VARCHAR2 (100 BYTE)  NOT NULL , 
     CODIGO                       VARCHAR2 (10 BYTE)  NOT NULL , 
     DEPARTAMENTO_ID_DEPARTAMENTO NUMBER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX CEM_USER.PK_MUNICIPIO ON CEM_USER.MUNICIPIO 
    ( 
     ID_MUNICIPIO ASC 
    ) 
;
CREATE UNIQUE INDEX CEM_USER.UK_MUNICIPIO_ID_DEPARTAMENTO ON CEM_USER.MUNICIPIO 
    ( 
     ID_MUNICIPIO ASC , 
     DEPARTAMENTO_ID_DEPARTAMENTO ASC 
    ) 
;

ALTER TABLE CEM_USER.MUNICIPIO 
    ADD CONSTRAINT MUNICIPIO_PK PRIMARY KEY ( ID_MUNICIPIO ) ;

ALTER TABLE CEM_USER.MUNICIPIO 
    ADD CONSTRAINT MUNICIPIO_ID_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO_UN UNIQUE ( ID_MUNICIPIO , DEPARTAMENTO_ID_DEPARTAMENTO ) ;

CREATE TABLE CEM_USER.PREGUNTAS 
    ( 
     ID_PREGUNTA        NUMBER  NOT NULL , 
     PREGUNTA_TEXTO     VARCHAR2 (500 BYTE)  NOT NULL , 
     RESPUESTA_A        VARCHAR2 (300 BYTE)  NOT NULL , 
     RESPUESTA_B        VARCHAR2 (300 BYTE)  NOT NULL , 
     RESPUESTA_C        VARCHAR2 (300 BYTE)  NOT NULL , 
     RESPUESTA_D        VARCHAR2 (300 BYTE)  NOT NULL , 
     RESPUESTA_CORRECTA CHAR (1 BYTE)  NOT NULL 
    ) 
;

ALTER TABLE CEM_USER.PREGUNTAS 
    ADD CONSTRAINT CHK_PREGUNTAS_CORRECTA 
    CHECK (RESPUESTA_CORRECTA IN ('A', 'B', 'C', 'D')) 
;
CREATE UNIQUE INDEX CEM_USER.PK_PREGUNTAS ON CEM_USER.PREGUNTAS 
    ( 
     ID_PREGUNTA ASC 
    ) 
;

ALTER TABLE CEM_USER.PREGUNTAS 
    ADD CONSTRAINT PREGUNTAS_PK PRIMARY KEY ( ID_PREGUNTA ) ;

CREATE TABLE CEM_USER.PREGUNTAS_PRACTICO 
    ( 
     ID_PREGUNTA_PRACTICO NUMBER  NOT NULL , 
     PREGUNTA_TEXTO       VARCHAR2 (500 BYTE)  NOT NULL , 
     PUNTEO               NUMBER  NOT NULL 
    ) 
;

ALTER TABLE CEM_USER.PREGUNTAS_PRACTICO 
    ADD CONSTRAINT CHK_PREGUNTAS_PRACTICO_PUNTEO 
    CHECK (punteo > 0) 
;
CREATE UNIQUE INDEX CEM_USER.PK_PREGUNTAS_PRACTICO ON CEM_USER.PREGUNTAS_PRACTICO 
    ( 
     ID_PREGUNTA_PRACTICO ASC 
    ) 
;

ALTER TABLE CEM_USER.PREGUNTAS_PRACTICO 
    ADD CONSTRAINT PREGUNTAS_PRACTICO_PK PRIMARY KEY ( ID_PREGUNTA_PRACTICO ) ;

CREATE TABLE CEM_USER.REGISTRO 
    ( 
     ID_REGISTRO                            NUMBER  NOT NULL , 
     UBICACION_ESCUELA_ID_ESCUELA           NUMBER  NOT NULL , 
     UBICACION_CENTRO_ID_CENTRO             NUMBER  NOT NULL , 
     MUNICIPIO_ID_MUNICIPIO                 NUMBER  NOT NULL , 
     MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO NUMBER  NOT NULL , 
     FECHA                                  DATE  NOT NULL , 
     TIPO_TRAMITE                           VARCHAR2 (100 BYTE)  NOT NULL , 
     TIPO_LICENCIA                          VARCHAR2 (5 BYTE)  NOT NULL , 
     NOMBRE_COMPLETO                        VARCHAR2 (200 BYTE)  NOT NULL , 
     GENERO                                 CHAR (1 BYTE)  NOT NULL 
    ) 
;

ALTER TABLE CEM_USER.REGISTRO 
    ADD CONSTRAINT CHK_REGISTRO_GENERO 
    CHECK (GENERO IN ('F', 'M')) 
;
CREATE UNIQUE INDEX CEM_USER.PK_REGISTRO ON CEM_USER.REGISTRO 
    ( 
     ID_REGISTRO ASC 
    ) 
;
CREATE UNIQUE INDEX CEM_USER.UK_REGISTRO_CONTEXTO ON CEM_USER.REGISTRO 
    ( 
     ID_REGISTRO ASC , 
     UBICACION_ESCUELA_ID_ESCUELA ASC , 
     UBICACION_CENTRO_ID_CENTRO ASC , 
     MUNICIPIO_ID_MUNICIPIO ASC , 
     MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO ASC 
    ) 
;

ALTER TABLE CEM_USER.REGISTRO 
    ADD CONSTRAINT REGISTRO_PK PRIMARY KEY ( ID_REGISTRO ) ;

ALTER TABLE CEM_USER.REGISTRO 
    ADD CONSTRAINT REGISTRO_ID_UBICACION_ESCUELA_UBICACION_CENTRO_MUNICIPIO_DEPARTAMENTO_ID UNIQUE ( ID_REGISTRO , UBICACION_ESCUELA_ID_ESCUELA , UBICACION_CENTRO_ID_CENTRO , MUNICIPIO_ID_MUNICIPIO , MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO ) ;

CREATE TABLE CEM_USER.RESPUESTA_PRACTICO_USUARIO 
    ( 
     PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO NUMBER  NOT NULL , 
     EXAMEN_ID_EXAMEN                        NUMBER  NOT NULL , 
     NOTA                                    NUMBER  NOT NULL 
    ) 
;

ALTER TABLE CEM_USER.RESPUESTA_PRACTICO_USUARIO 
    ADD CONSTRAINT CHK_RESP_PRACTICO_NOTA 
    CHECK (nota >= 0) 
;
CREATE UNIQUE INDEX CEM_USER.PK_RESPUESTA_PRACTICO_USUARIO ON CEM_USER.RESPUESTA_PRACTICO_USUARIO 
    ( 
     PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO ASC , 
     EXAMEN_ID_EXAMEN ASC 
    ) 
;

ALTER TABLE CEM_USER.RESPUESTA_PRACTICO_USUARIO 
    ADD CONSTRAINT RESPUESTA_PRACTICO_USUARIO_PK PRIMARY KEY ( PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO, EXAMEN_ID_EXAMEN ) ;

CREATE TABLE CEM_USER.RESPUESTA_USUARIO 
    ( 
     PREGUNTAS_ID_PREGUNTA NUMBER  NOT NULL , 
     EXAMEN_ID_EXAMEN      NUMBER  NOT NULL , 
     RESPUESTA             CHAR (1 BYTE)  NOT NULL 
    ) 
;

ALTER TABLE CEM_USER.RESPUESTA_USUARIO 
    ADD CONSTRAINT CHK_RESP_USUARIO_RESPUESTA 
    CHECK (RESPUESTA IN ('A', 'B', 'C', 'D')) 
;
CREATE UNIQUE INDEX CEM_USER.PK_RESPUESTA_USUARIO ON CEM_USER.RESPUESTA_USUARIO 
    ( 
     PREGUNTAS_ID_PREGUNTA ASC , 
     EXAMEN_ID_EXAMEN ASC 
    ) 
;

ALTER TABLE CEM_USER.RESPUESTA_USUARIO 
    ADD CONSTRAINT RESPUESTA_USUARIO_PK PRIMARY KEY ( PREGUNTAS_ID_PREGUNTA, EXAMEN_ID_EXAMEN ) ;

CREATE TABLE CEM_USER.UBICACION 
    ( 
     ESCUELA_ID_ESCUELA NUMBER  NOT NULL , 
     CENTRO_ID_CENTRO   NUMBER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX CEM_USER.PK_UBICACION ON CEM_USER.UBICACION 
    ( 
     ESCUELA_ID_ESCUELA ASC , 
     CENTRO_ID_CENTRO ASC 
    ) 
;

ALTER TABLE CEM_USER.UBICACION 
    ADD CONSTRAINT UBICACION_PK PRIMARY KEY ( ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO ) ;

ALTER TABLE CEM_USER.EXAMEN 
    ADD CONSTRAINT EXAMEN_CORRELATIVO_FK FOREIGN KEY 
    ( 
     CORRELATIVO_ID_CORRELATIVO
    ) 
    REFERENCES CEM_USER.CORRELATIVO 
    ( 
     ID_CORRELATIVO
    ) 
;

ALTER TABLE CEM_USER.EXAMEN 
    ADD CONSTRAINT EXAMEN_REGISTRO_FK FOREIGN KEY 
    ( 
     REGISTRO_ID_REGISTRO,
     REGISTRO_UBICACION_ESCUELA_ID_ESCUELA,
     REGISTRO_UBICACION_CENTRO_ID_CENTRO,
     REGISTRO_MUNICIPIO_ID_MUNICIPIO,
     REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO
    ) 
    REFERENCES CEM_USER.REGISTRO 
    ( 
     ID_REGISTRO,
     UBICACION_ESCUELA_ID_ESCUELA,
     UBICACION_CENTRO_ID_CENTRO,
     MUNICIPIO_ID_MUNICIPIO,
     MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO
    ) 
;

ALTER TABLE CEM_USER.MUNICIPIO 
    ADD CONSTRAINT MUNICIPIO_DEPARTAMENTO_FK FOREIGN KEY 
    ( 
     DEPARTAMENTO_ID_DEPARTAMENTO
    ) 
    REFERENCES CEM_USER.DEPARTAMENTO 
    ( 
     ID_DEPARTAMENTO
    ) 
;

ALTER TABLE CEM_USER.REGISTRO 
    ADD CONSTRAINT REGISTRO_MUNICIPIO_FK FOREIGN KEY 
    ( 
     MUNICIPIO_ID_MUNICIPIO,
     MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO
    ) 
    REFERENCES CEM_USER.MUNICIPIO 
    ( 
     ID_MUNICIPIO,
     DEPARTAMENTO_ID_DEPARTAMENTO
    ) 
;

ALTER TABLE CEM_USER.REGISTRO 
    ADD CONSTRAINT REGISTRO_UBICACION_FK FOREIGN KEY 
    ( 
     UBICACION_ESCUELA_ID_ESCUELA,
     UBICACION_CENTRO_ID_CENTRO
    ) 
    REFERENCES CEM_USER.UBICACION 
    ( 
     ESCUELA_ID_ESCUELA,
     CENTRO_ID_CENTRO
    ) 
;

ALTER TABLE CEM_USER.RESPUESTA_PRACTICO_USUARIO 
    ADD CONSTRAINT RESPUESTA_PRACTICO_USUARIO_EXAMEN_FK FOREIGN KEY 
    ( 
     EXAMEN_ID_EXAMEN
    ) 
    REFERENCES CEM_USER.EXAMEN 
    ( 
     ID_EXAMEN
    ) 
;

ALTER TABLE CEM_USER.RESPUESTA_PRACTICO_USUARIO 
    ADD CONSTRAINT RESPUESTA_PRACTICO_USUARIO_PREGUNTAS_PRACTICO_FK FOREIGN KEY 
    ( 
     PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO
    ) 
    REFERENCES CEM_USER.PREGUNTAS_PRACTICO 
    ( 
     ID_PREGUNTA_PRACTICO
    ) 
;

ALTER TABLE CEM_USER.RESPUESTA_USUARIO 
    ADD CONSTRAINT RESPUESTA_USUARIO_EXAMEN_FK FOREIGN KEY 
    ( 
     EXAMEN_ID_EXAMEN
    ) 
    REFERENCES CEM_USER.EXAMEN 
    ( 
     ID_EXAMEN
    ) 
;

ALTER TABLE CEM_USER.RESPUESTA_USUARIO 
    ADD CONSTRAINT RESPUESTA_USUARIO_PREGUNTAS_FK FOREIGN KEY 
    ( 
     PREGUNTAS_ID_PREGUNTA
    ) 
    REFERENCES CEM_USER.PREGUNTAS 
    ( 
     ID_PREGUNTA
    ) 
;

ALTER TABLE CEM_USER.UBICACION 
    ADD CONSTRAINT UBICACION_CENTRO_FK FOREIGN KEY 
    ( 
     CENTRO_ID_CENTRO
    ) 
    REFERENCES CEM_USER.CENTRO 
    ( 
     ID_CENTRO
    ) 
;

ALTER TABLE CEM_USER.UBICACION 
    ADD CONSTRAINT UBICACION_ESCUELA_FK FOREIGN KEY 
    ( 
     ESCUELA_ID_ESCUELA
    ) 
    REFERENCES CEM_USER.ESCUELA 
    ( 
     ID_ESCUELA
    ) 
;

CREATE SEQUENCE CEM_USER.CENTRO_ID_CENTRO_SEQ 
START WITH 1 
    CACHE 20 ;

CREATE OR REPLACE TRIGGER CEM_USER.CENTRO_ID_CENTRO_TRG 
BEFORE INSERT ON CEM_USER.CENTRO 
FOR EACH ROW 
WHEN (NEW.ID_CENTRO IS NULL) 
BEGIN 
    :NEW.ID_CENTRO := CEM_USER.CENTRO_ID_CENTRO_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE CEM_USER.CORRELATIVO_ID_CORRELATIVO_SEQ 
START WITH 1 
    CACHE 20 ;

CREATE OR REPLACE TRIGGER CEM_USER.CORRELATIVO_ID_CORRELATIVO_TRG 
BEFORE INSERT ON CEM_USER.CORRELATIVO 
FOR EACH ROW 
WHEN (NEW.ID_CORRELATIVO IS NULL) 
BEGIN 
    :NEW.ID_CORRELATIVO := CEM_USER.CORRELATIVO_ID_CORRELATIVO_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE CEM_USER.DEPARTAMENTO_ID_DEPARTAMENTO_SEQ 
START WITH 1 
    CACHE 20 ;

CREATE OR REPLACE TRIGGER CEM_USER.DEPARTAMENTO_ID_DEPARTAMENTO_TRG 
BEFORE INSERT ON CEM_USER.DEPARTAMENTO 
FOR EACH ROW 
WHEN (NEW.ID_DEPARTAMENTO IS NULL) 
BEGIN 
    :NEW.ID_DEPARTAMENTO := CEM_USER.DEPARTAMENTO_ID_DEPARTAMENTO_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE CEM_USER.ESCUELA_ID_ESCUELA_SEQ 
START WITH 1 
    CACHE 20 ;

CREATE OR REPLACE TRIGGER CEM_USER.ESCUELA_ID_ESCUELA_TRG 
BEFORE INSERT ON CEM_USER.ESCUELA 
FOR EACH ROW 
WHEN (NEW.ID_ESCUELA IS NULL) 
BEGIN 
    :NEW.ID_ESCUELA := CEM_USER.ESCUELA_ID_ESCUELA_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE CEM_USER.EXAMEN_ID_EXAMEN_SEQ 
START WITH 1 
    CACHE 20 ;

CREATE OR REPLACE TRIGGER CEM_USER.EXAMEN_ID_EXAMEN_TRG 
BEFORE INSERT ON CEM_USER.EXAMEN 
FOR EACH ROW 
WHEN (NEW.ID_EXAMEN IS NULL) 
BEGIN 
    :NEW.ID_EXAMEN := CEM_USER.EXAMEN_ID_EXAMEN_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE CEM_USER.MUNICIPIO_ID_MUNICIPIO_SEQ 
START WITH 1 
    CACHE 20 ;

CREATE OR REPLACE TRIGGER CEM_USER.MUNICIPIO_ID_MUNICIPIO_TRG 
BEFORE INSERT ON CEM_USER.MUNICIPIO 
FOR EACH ROW 
WHEN (NEW.ID_MUNICIPIO IS NULL) 
BEGIN 
    :NEW.ID_MUNICIPIO := CEM_USER.MUNICIPIO_ID_MUNICIPIO_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE CEM_USER.PREGUNTAS_ID_PREGUNTA_SEQ 
START WITH 1 
    CACHE 20 ;

CREATE OR REPLACE TRIGGER CEM_USER.PREGUNTAS_ID_PREGUNTA_TRG 
BEFORE INSERT ON CEM_USER.PREGUNTAS 
FOR EACH ROW 
WHEN (NEW.ID_PREGUNTA IS NULL) 
BEGIN 
    :NEW.ID_PREGUNTA := CEM_USER.PREGUNTAS_ID_PREGUNTA_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE CEM_USER.PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO_SEQ 
START WITH 1 
    CACHE 20 ;

CREATE OR REPLACE TRIGGER CEM_USER.PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO_TRG 
BEFORE INSERT ON CEM_USER.PREGUNTAS_PRACTICO 
FOR EACH ROW 
WHEN (NEW.ID_PREGUNTA_PRACTICO IS NULL) 
BEGIN 
    :NEW.ID_PREGUNTA_PRACTICO := CEM_USER.PREGUNTAS_PRACTICO_ID_PREGUNTA_PRACTICO_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE CEM_USER.REGISTRO_ID_REGISTRO_SEQ 
START WITH 1 
    CACHE 20 ;

CREATE OR REPLACE TRIGGER CEM_USER.REGISTRO_ID_REGISTRO_TRG 
BEFORE INSERT ON CEM_USER.REGISTRO 
FOR EACH ROW 
WHEN (NEW.ID_REGISTRO IS NULL) 
BEGIN 
    :NEW.ID_REGISTRO := CEM_USER.REGISTRO_ID_REGISTRO_SEQ.NEXTVAL; 
END;
/



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                            17
-- ALTER TABLE                             33
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           9
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          9
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
